name: Build with Jekyll

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: false
      - name: install bundler
        run: gem install bundler
      - name: bundle install
        run: bundle install
      - name: build website
        run: bundle exec jekyll build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site
          path: _site
